GET http://localhost:3000/sample

### get user
GET http://localhost:3000/user?phone=01627001665
token: g51b9nqv2q8by4cpkdyw

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "01627001665",
  "password": "123456",
  "tosAgreement": true
}

### update user
PUT http://localhost:3000/user
Content-Type: application/json
token: g51b9nqv2q8by4cpkdyw

{
    "firstName": "Lemon",
    "lastName": "Cush",
    "phone": "01627001665",
    "password": "123456",
    "tosAgreement": true
}

### delete user
DELETE http://localhost:3000/user?phone=01627001665
token: g51b9nqv2q8by4cpkdyw






### Authentication

### create token
POST http://localhost:3000/token
Content-Type: application/json

{
  "phone":"01627001665",
  "password":"123456"
}

### get token
GET http://localhost:3000/token?id=g51b9nqv2q8by4cpkdyw

### update token
PUT http://localhost:3000/token
Content-Type: application/json

{
  "id":"g51b9nqv2q8by4cpkdyw",
  "extend":true
}

### Delete token
DELETE  http://localhost:3000/token?id=g51b9nqv2q8by4cpkdyw



### checks

### create checks
POST http://localhost:3000/check
Content-Type: application/json
token: g51b9nqv2q8by4cpkdyw

{
  "protocol":"https",
  "url":"google.com",
  "method":"GET",
  "successCodes":[200,201],
  "timeoutSeconds":2
}

### get checks data
GET http://localhost:3000/check
token: g51b9nqv2q8by4cpkdyw

### Update checks
PUT http://localhost:3000/check
Content-Type: application/json
token: g51b9nqv2q8by4cpkdyw

{
  "id":"f00596vavjtq7lcvrwmw",
  "protocol":"https",
  "url":"google.com",
  "method":"POST",
  "successCodes":[200,201],
  "timeoutSeconds":2
}

### Delete check
DELETE  http://localhost:3000/check?id=melnkpajprwjjhhd8foo
Content-Type: application/json
token: g51b9nqv2q8by4cpkdyw
