GET http://localhost:3000/sample

### get user
GET http://localhost:3000/user?phone=01627001665
token: fmwgw7j7gg10uuvbbfxn

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "01627001665",
  "password": "123456",
  "tosAgreement": true
}

### update user
PUT http://localhost:3000/user
Content-Type: application/json
token: fmwgw7j7gg10uuvbbfxn

{
    "firstName": "Lemon",
    "lastName": "Cush",
    "phone": "01627001665",
    "password": "123456",
    "tosAgreement": true
}

### delete user
DELETE http://localhost:3000/user?phone=01627001665
token: fmwgw7j7gg10uuvbbfxn






### Authentication

### create token
POST http://localhost:3000/token
Content-Type: application/json

{
  "phone":"01627001665",
  "password":"123456"
}

### get token
GET http://localhost:3000/token?id=fmwgw7j7gg10uuvbbfxn

### update token
PUT http://localhost:3000/token
Content-Type: application/json

{
  "id":"fmwgw7j7gg10uuvbbfxn",
  "extend":true
}

### Delete token
DELETE  http://localhost:3000/token?id=fmwgw7j7gg10uuvbbfxn



### checks

### create checks
POST http://localhost:3000/check
Content-Type: application/json
token: fmwgw7j7gg10uuvbbfxn

{
  "protocol":"https",
  "url":"google.com",
  "method":"GET",
  "successCodes":[200,201],
  "timeoutSeconds":2
}